# Generated by Django 5.2.6 on 2025-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('district_leader', 'District Leader')], max_length=20)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
